// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg_OLoYOkBmJzYfo_C2AaYeFW56pXox8s',
    appId: '1:689679622866:web:fdf58ba30c4610b603430b',
    messagingSenderId: '689679622866',
    projectId: 'group4chatapp',
    authDomain: 'group4chatapp.firebaseapp.com',
    storageBucket: 'group4chatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM3D_hFDIfvF-kB8kmS8apfKQJZ1vK6uc',
    appId: '1:689679622866:android:46f871bbd5cab9ed03430b',
    messagingSenderId: '689679622866',
    projectId: 'group4chatapp',
    storageBucket: 'group4chatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuGwglyVqbZ4BmI0uStpjl0tSj9I9D-ls',
    appId: '1:689679622866:ios:a22e23a13ae4bd8e03430b',
    messagingSenderId: '689679622866',
    projectId: 'group4chatapp',
    storageBucket: 'group4chatapp.firebasestorage.app',
    iosBundleId: 'com.example.group4ChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuGwglyVqbZ4BmI0uStpjl0tSj9I9D-ls',
    appId: '1:689679622866:ios:a22e23a13ae4bd8e03430b',
    messagingSenderId: '689679622866',
    projectId: 'group4chatapp',
    storageBucket: 'group4chatapp.firebasestorage.app',
    iosBundleId: 'com.example.group4ChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg_OLoYOkBmJzYfo_C2AaYeFW56pXox8s',
    appId: '1:689679622866:web:a585defcf1b4234003430b',
    messagingSenderId: '689679622866',
    projectId: 'group4chatapp',
    authDomain: 'group4chatapp.firebaseapp.com',
    storageBucket: 'group4chatapp.firebasestorage.app',
  );
}
